version: "3.9"
services:
  multipan:
    container_name: multipan
    image: antoniocifu/ihost-multipan-docker:latest
    restart: unless-stopped
    privileged: true # don't change this !
    network_mode: host # don't change this !
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ~/multipan/:/data
    environment:
      DEVICE: "/dev/ttyUSB0" # only change if your have multiple devices
      BAUDRATE: "115200"
      FLOW_CONTROL: "false" # set true if your dongle requires it

      BACKBONE_IF: "eth0" # change this to your network interface
      OTBR_REST_LISTEN_PORT: "8081" # use this within the HomeAssistant integration
      OTBR_WEB_PORT: "8086"

      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108" #

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 0 # change to 1 for firmware update
      # FIRMWARE: "donglee_mg21_multipan_beta_4.6.0_115200.gbl"
