name: 'build latest'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  UPSTREAM_REPO: ihost-open-source-project/hassio-ihost-silabs-multiprotocol-amd64

jobs:
  get_versions:
    runs-on: ubuntu-latest
    outputs:
      base_version: ${{ steps.base_version.outputs.base_version }}
      self_version: ${{ steps.self_version.outputs.self_version }}
    steps:
      - name: base version (from GHCR tags)
        id: base_version
        run: |
          TOKEN=$(curl -fsSL -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/token?service=ghcr.io&scope=repository:${{ env.UPSTREAM_REPO }}:pull" | jq -r '.token')
          TAGS_JSON=$(curl -fsSL -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/${{ env.UPSTREAM_REPO }}/tags/list")
          BASE_TAG=$(echo "$TAGS_JSON" | jq -r '.tags | map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) | sort_by((split(".")|map(tonumber))) | last')
          echo base_version=${BASE_TAG:-1.0.0} >> $GITHUB_OUTPUT

      - name: show base version
        run: |
          echo ${{ steps.base_version.outputs.base_version }}

      - name: self version
        id: self_version
        run: |
          docker pull antoniocifu/ihost-multipan-docker:latest
          echo self_version=$(docker inspect antoniocifu/ihost-multipan-docker:latest --format '{{ index .Config.Labels "org.opencontainers.image.version"}}') >> $GITHUB_OUTPUT

      - name: show self version
        run: |
          echo ${{ steps.self_version.outputs.self_version }}

  trigger_build:
    runs-on: ubuntu-latest
    needs: get_versions
    permissions: write-all
    name: trigger build for ${{ needs.get_versions.outputs.base_version }}
    if: needs.get_versions.outputs.base_version != needs.get_versions.outputs.self_version || github.event_name == 'workflow_dispatch'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: build_version
          client-payload: '{"base_version": "${{ needs.get_versions.outputs.base_version }}", "is_latest": "yes"}'
